### ISSUE TITLE
Non-functioning page

### ISSUE THREAD

**Issue by nocomicsans** [jakemclelland/romanizer#7]
When text is pasted and I click "Go", nothing appears in the second field. The page doesn't appear to process the command. 

I'm using Safari Version 16.1 (18614.2.9.1.12) on MacOS 13.0.1 (22A400)

<img width="384" alt="Screenshot 2022-12-26 at 10 57 34 AM" src="https://user-images.githubusercontent.com/9904890/209565688-e0d21744-64e5-4f66-a693-2c91a38609ad.png">

**Comment by jakemclelland** [comment]
This has been corrected.
