### ISSUE TITLE
Bug in Western Armenian

### ISSUE THREAD

**Issue by nocomicsans** [jakemclelland/romanizer#8]
Demonstration of the problem: 
<img width="1055" alt="Screenshot 2023-02-07 at 12 24 01 PM" src="https://user-images.githubusercontent.com/9904890/217318834-ceb3a2c6-b9d7-4484-9cb3-aba11ed9c334.png">

There's a character in this text that isn't defined in your set:
```
Տպագրեալ ի հայրապետութեան Տ․ Տ․ Ներսիսի 
ազգասեր եւ աստուածընտիր կաթողիկոսի ամենայն հայոց եւ ի պատրիարքութեան սրբոյ Երուսաղէմի Տ․ Յովհաննու սրբազան արքեպիսկոպոսի եւ ի պատրիարքութեան կոստանդնուպօլսոյ Տ․ Յակոբայ ազգասեր եւ վեհափառ  արքեպիսկոպոսի
```

**Comment by jakemclelland** [comment]
Working on it

**Comment by jakemclelland** [comment]
@nocomicsans Thanks for bringing this to our attention.
Sorry for any inconvenience.
This problem has been resolved.
